language: node_js

node_js:
  - "10"

dist: xenial

cache: npm

before_install:
  - echo always-auth=true > .npmrc
  - echo registry=https://packagecloud.io/ratehub/npm/npm/ >> .npmrc
  - echo //packagecloud.io/ratehub/npm/npm/:_authToken="\${PACKAGECLOUD_TOKEN}" >> .npmrc

install:
  - npm install
script:
  - npm publish
