name: Publish

on:
  push:
    branches:
      - 'migrate-gh-actions'

env:
  PACKAGECLOUD_TOKEN: ${{ secrets.PACKAGECLOUD_TOKEN }}
  NODE_AUTH_TOKEN: ${{ secrets.PACKAGECLOUD_TOKEN }}

jobs:
  publish:
    name: Publish npm package
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '10'
        registry-url: 'https://packagecloud.io/ratehub/npm/npm/'
        scope: '@ratehub'
    - name: Configure read only access to a private NPM registry
      run: |
        echo always-auth=true > .npmrc
        echo //packagecloud.io/ratehub/npm/npm/:_authToken=${{ secrets.PACKAGECLOUD_TOKEN }} >> .npmrc
    - name: Install dependencies
      run: |
        npm install
        npm publish

